baseURL = 'https://www.hanxic.com/'
languageCode = 'en-us'
title = 'Hanxi "Gary" Chen'

[menus]
  [[menus.main]]
    name = 'About'
    url = '/#about'
    weight = 10
    [menus.main.params]
      section = 'about'

  [[menus.main]]
    name = 'Publications'
    url = '/#publications'
    weight = 20
    [menus.main.params]
      section = 'publications'

  [[menus.main]]
    name = 'Research'
    url = '/#research'
    weight = 30
    [menus.main.params]
      section = 'research'

  [[menus.main]]
    name = 'Education'
    url = '/#education'
    weight = 40
    [menus.main.params]
      section = 'education'

  [[menus.main]]
    name = 'Teaching'
    url = '/#teaching'
    weight = 50
    [menus.main.params]
      section = 'teaching'

  [[menus.main]]
    name = 'Service'
    url = '/#service'
    weight = 60
    [menus.main.params]
      section = 'service'

  [[menus.main]]
    name = 'Contact'
    url = '/#contact'
    weight = 70
    [menus.main.params]
      section = 'contact'

  # [[menus.main]]
  #   name = 'Tags'
  #   pageRef = '/tags'
  #   weight = 30

[params]
  cvURL = '/cv/hanxi-chen-cv.pdf'
  profilePicture = "images/profile picture.jpg"
  updateTime = "August 2026"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
